default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres

development:
  <<: *default
  database: cap_development

test:
  <<: *default
  database: cap_test

production:
  <<: *default
  database: cap_production
  username: cap
  password: <%= ENV["CAP_DATABASE_PASSWORD"] %>
